language: rust
sudo: false

rust:
# Explicitly test against minimum Rust version to avoid accidentally breaking
# compatibility.
- 1.25.0
- stable
- beta
- nightly
env:
- FEATURE_ARGS=''
- FEATURE_ARGS='--lib --no-default-features'

matrix:
  include:
  # `rustfmt` verification.
  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  # `clippy` lint tests.
  - rust: nightly
    script:
    # `clippy` may fail to build with certain nightly toolchain releases, so
    # ignore lint tests if this happens.
    - if cargo install clippy; then cargo clippy; fi
  # The `alloc` feature should have no effect when `std` is also enabled, but
  # we should include builds with both enabled anyway to ensure no
  # side-effects are caused.
  - rust: nightly
    env: FEATURE_ARGS='--features alloc'
  - rust: nightly
    env: FEATURE_ARGS='--features alloc --lib --no-default-features'
  - rust: nightly
    env: FEATURE_ARGS='--features unstable'
  - rust: nightly
    env: FEATURE_ARGS='--features unstable --lib --no-default-features'
  - rust: nightly
    env: FEATURE_ARGS='--features "alloc unstable"'
  - rust: nightly
    env: FEATURE_ARGS='--features "alloc unstable" --lib --no-default-features'

script:
- cargo test $FEATURE_ARGS --verbose
- cargo test $FEATURE_ARGS --verbose --release

notifications:
  email:
    on_success: never
