language: rust
sudo: false

rust:
# Explicitly test against minimum Rust version to avoid accidentally breaking
# compatibility.
- 1.25.0
- stable
- beta
- nightly
env:
- FEATURES="" OTHER_ARGS=""
- FEATURES="" OTHER_ARGS="--lib --no-default-features"

matrix:
  include:
  # `rustfmt` verification.
  - rust: stable
    before_script:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check
  # `clippy` lint tests.
  - rust: stable
    before_script:
    - rustup component add clippy
    script:
    - cargo clippy -- -Dwarnings
  # The `alloc` feature should have no effect when `std` is also enabled, but
  # we should include builds with both enabled anyway to ensure no
  # side-effects are caused.
  - rust: nightly
    env: FEATURES="alloc" OTHER_ARGS=""
  - rust: nightly
    env: FEATURES="alloc" OTHER_ARGS="--lib --no-default-features"
  - rust: nightly
    env: FEATURES="unstable" OTHER_ARGS=""
  - rust: nightly
    env: FEATURES="unstable" OTHER_ARGS="--lib --no-default-features"
  - rust: nightly
    env: FEATURES="alloc unstable" OTHER_ARGS=""
  - rust: nightly
    env: FEATURES="alloc unstable" OTHER_ARGS="--lib --no-default-features"

script:
- cargo test --features "$FEATURES" $OTHER_ARGS --verbose
- cargo test --features "$FEATURES" $OTHER_ARGS --verbose --release

notifications:
  email:
    on_success: never
